version: "3.4"

services:
  api:
    container_name: manonaya-api
    build:
      dockerfile: ../docker/api.Dockerfile
      context: ../api
    expose:
      - 5000
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://db:27017/theorapy
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    depends_on:
      - db

  db:
    container_name: manonaya-database
    image: mongo:latest
    logging:
      driver: none

  client:
    container_name: manonaya-client
    stdin_open: true
    ports:
      - 3000:80
    build:
      dockerfile: ../docker/client.Dockerfile
      context: ../client
    environment:
      - REACT_APP_API_URI=api
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
